version: 1.4.0.{build}
image: Visual Studio 2022

configuration: Release

platform:
- Win32
- x64
- ARM64

environment:
  PFX_ENC_PASS:
    secure: vl0ntw9DjQdAno9nYVe0osg2tBmXD7gW75NLfxIvxMDW3GiVlJlFcESf7v6f7qKe
  PFX_PASS:
    secure: rgMy2ixSiaW0sk2CwaHwO5pK8U98ynzt/jjiGNRSYPfaAcOTRZ5oX+fsgqn6qP54

cache:
  - vcpkg_installed -> vcpkg.json
  - '%LOCALAPPDATA%\vcpkg\archives -> vcpkg.json'

for:

-
  branches:
    only:
      - /version-.*/

  skip_non_tags: true

init:
- ps: >-
    if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -match '^l10n_') {
      Write-Host 'Skipping translation branch pull request'
      Exit-AppveyorBuild
    }

# Decrypt the code signing certificate.
install:
- cmd: >-
    git submodule init

    git submodule update

    .\Explorer++\ThirdParty\vcpkg\bootstrap-vcpkg.bat

    nuget install secure-file -ExcludeVersion

    IF DEFINED PFX_ENC_PASS (secure-file\tools\secure-file -decrypt %APPVEYOR_BUILD_FOLDER%\authenticode.pfx.enc -secret %PFX_ENC_PASS%)

before_build:
- ps: >-
    if (Test-Path env:APPVEYOR_REPO_TAG_NAME) {
      if ($env:APPVEYOR_REPO_TAG_NAME -match '-beta(-\d)?$') {
        $env:RELEASE_MODE = 'beta'
      } else {
        $env:RELEASE_MODE = 'stable'
      }
    }

build:
  project: Explorer++\Explorer++.sln
  verbosity: minimal

# Sign and package the executable.
after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%


    IF "%PLATFORM%" == "Win32" ( SET "arch=x86" ) ELSE IF "%PLATFORM%" == "x64" ( SET "arch=x64" ) ELSE IF "%PLATFORM%" == "ARM64" ( SET "arch=arm64" )


    SET "archiveName=explorerpp_%arch%.zip"


    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Explorer++\Explorer++\%PLATFORM%\%CONFIGURATION%\Explorer++.exe

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\History.txt

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\License.txt

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\Readme.txt


    7z a explorerpp_%arch%_symbols.zip %APPVEYOR_BUILD_FOLDER%\Explorer++\Explorer++\%PLATFORM%\%CONFIGURATION%\Explorer++.pdb


    IF NOT "%PLATFORM%" == "ARM64" ( copy "%APPVEYOR_BUILD_FOLDER%\Explorer++\Installer\bin\%arch%\%CONFIGURATION%\explorerpp_%arch%_setup.msi" . )


    7z a explorerpp_translations.zip %APPVEYOR_BUILD_FOLDER%\Explorer++\Win32\%CONFIGURATION%\Explorer++*.dll


    (echo.|set /p="%APPVEYOR_BUILD_VERSION%")>latest_version.txt || ver>nul

test_script:
- ps: >-
    if ($env:PLATFORM -ne "ARM64") {
        cd $env:APPVEYOR_BUILD_FOLDER\Explorer++\TestExplorer++\$env:PLATFORM\$env:CONFIGURATION


        # Run the tests.

        .\TestExplorer++.exe --gtest_output=xml:TestExplorer++Output.xml


        # Upload results to AppVeyor.

        $wc = New-Object 'System.Net.WebClient'

        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestExplorer++Output.xml))
    }

artifacts:
- path: explorerpp_x86.zip
- path: explorerpp_x86_symbols.zip
- path: explorerpp_x64.zip
- path: explorerpp_x64_symbols.zip
- path: explorerpp_arm64.zip
- path: explorerpp_arm64_symbols.zip
- path: explorerpp_x86_setup.msi
- path: explorerpp_x64_setup.msi
- path: explorerpp_translations.zip
- path: latest_version.txt

before_deploy:
- ps: >-
    $versionComponents = $env:APPVEYOR_BUILD_VERSION -split '\.'

    $versionComponents = $versionComponents[0, 1, 2]

    $releaseBuildVersion = $versionComponents -join '.'

    if ($env:APPVEYOR_REPO_TAG_NAME -match '-beta(-\d)?$') {
      $env:RELEASE_TITLE = "Explorer++ $releaseBuildVersion beta"
      $env:PRERELEASE = $true
    } else {
      $env:RELEASE_TITLE = "Explorer++ $releaseBuildVersion"
      $env:PRERELEASE = $false
    }

deploy:
  - provider: GitHub
    auth_token:
      secure: iU7ijPhvPEwymBKhGsZBwD9aDO3yPWpAq8iS5vaQcs5YdLRgcICuLOEJZ9UZIh9l
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(RELEASE_TITLE)
    prerelease: $(PRERELEASE)
    description: ''
    artifact: /.*\.zip/
    force_update: true
    draft: true
    on:
      APPVEYOR_REPO_TAG: true

  - provider: S3
    access_key_id:
      secure: C7kIRfyPAfkKkpF7Gh7BqEvqZVMMi2Ps0+iGFgCTiKE=
    secret_access_key:
      secure: agLWDF321Coa4wU5Wa07pwLm0QLQ2KPj9M0Ys5vVlOQID3+TDUtrvRX2R47yZbFJ
    bucket: explorerplusplus-builds
    region: us-east-1
    folder: dev/$(APPVEYOR_BUILD_VERSION)
    artifact: /.*\.zip|.*\.msi/
    set_content_type: true
    on:
      APPVEYOR_REPO_TAG: false

  - provider: S3
    access_key_id:
      secure: C7kIRfyPAfkKkpF7Gh7BqEvqZVMMi2Ps0+iGFgCTiKE=
    secret_access_key:
      secure: agLWDF321Coa4wU5Wa07pwLm0QLQ2KPj9M0Ys5vVlOQID3+TDUtrvRX2R47yZbFJ
    bucket: explorerplusplus-builds
    region: us-east-1
    folder: dev
    artifact: latest_version.txt
    set_content_type: true
    on:
      APPVEYOR_REPO_TAG: false